name:                utility
version:             0.1.0.0
github:              "cohei/haskell-utility"
license:             BSD3
author:              "TANIGUCHI Kohei"
maintainer:          "a.d.xvii.kal.mai@gmail.com"
copyright:           "2018 TANIGUCHI Kohei"

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wmissing-import-lists
  - -Wmissing-local-signatures
  - -Wmonomorphism-restriction
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fdefer-typed-holes

library:
  source-dirs: src
  ghc-options: -O0

tests:
  doctest:
    source-dirs: test
    main: doctests.hs
    other-modules: []
    dependencies:
      - doctest
  hspec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - utility
      - hspec
    build-tools:
      - hspec-discover
