version: 2
jobs:
  build:
    docker:
      - image: haskell:8.8.1
    steps:
      - checkout
      - restore_cache:
         keys:
           - dependency-{{ checksum "utility.cabal" }}
           - dependency
      - run: cabal update
      - run: HSPEC_OPTIONS=--color cabal test
      - save_cache:
          key: dependency-{{ checksum "utility.cabal" }}
          paths:
            - "~/.cabal"
      - run: cabal haddock --haddock-option=--odir=haddock
      - store_artifacts:
          path: haddock
          destination: haddock
