version: 2
jobs:
  build:
    docker:
      - image: haskell:8.4.3
    steps:
      - checkout
      - restore_cache:
         keys:
           - stack
      - run: stack test
      - save_cache:
          key: stack
          paths:
            - "~/.stack"
