version: 2
jobs:
  build:
    docker:
      - image: haskell:8.4.3
    steps:
      - checkout
      - restore_cache:
         keys:
           - stack-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
           - stack-{{ checksum "stack.yaml" }}
           - stack
      - run: stack test
      - save_cache:
          key: stack-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "~/.stack"
      - run: stack haddock --haddock-arguments="--odir=haddock"
      - store_artifacts:
          path: haddock
          destination: haddock
