version: 2
jobs:
  build:
    docker:
      - image: haskell:8.6.3
    steps:
      - checkout
      - restore_cache:
         keys:
           - dependency-{{ checksum "utility.cabal" }}
           - dependency
      - run: cabal new-update
      - run: HSPEC_OPTIONS=--color cabal new-test
      - save_cache:
          key: dependency-{{ checksum "utility.cabal" }}
          paths:
            - "~/.cabal"
      - run: cabal new-haddock --haddock-option=--odir=haddock
      - store_artifacts:
          path: haddock
          destination: haddock
